### ISSUE TITLE
Local stations not found

### ISSUE THREAD

**Issue by noerw** [juliuste/oebb-hafas#3]
I noticed that this package provides less data than what is available in the ÖBB scotty app.
So far I mostly noticed this with local (bus) stops, but I didn't survey carefully yet..

1. `nearby({ type: 'location', longitude: 14.62285, latitude: 48.04282 })`
  returns no stops at all (should return bus stop "St. Peter in der Au-Markt")

2. `nearby({ type: 'location', longitude: 14.301417, latitude: 48.285179 })`
  provides data about stations like `Linz/Donau Bulgariplatz` (stop 8171124),
  but using it in `journeys()` results in `INVALID_REQUEST`, `HCI Service: location missing or invalid`

The stations mentioned above are present in the ÖBB Scotty app and also return journeys, so I am wondering if there is something wrong with the oebb profile..

**Comment by juliuste** [comment]
@derhuerst fyi

**Comment by noerw** [comment]
Okay never mind, I must've been doing something wrong, now it works ¯\_(ツ)_/¯

**Comment by derhuerst** [comment]
Can you explain what the problem was, so that others can learn from that? Thanks!

**Comment by noerw** [comment]
I reverted the change from db profile to oebb profile without noticing 🙃
Turns out, db-hafas also provides a lot of data in austria, but not all
